blank_issues_enabled: true
contact_links:
  - name: 💬 Dúvidas e Discussões
    url: https://github.com/nfbrentano/feature-descriptors/discussions
    about: Faça perguntas ou troque ideias com a comunidade.
